### ISSUE TITLE
When I visit 'oauth2/token', report the following error.

### ISSUE THREAD

**Issue by umono** [hosannahighertech/yii2-oauth2-server#4] opened 2018-06-12 15:33 UTC
```json
{
    "name": "Exception",
    "message": "Argument 1 passed to OAuth2\\Server::handleTokenRequest() must be an instance of OAuth2\\RequestInterface, instance of yii\\web\\Request given, called in /Users/moment/work/code/work-jy/shop-admin/vendor/filsh/yii2-oauth2-server/Server.php on line 42",
    "code": 0,
    "type": "TypeError",
    "file": "/Users/moment/work/code/work-jy/shop-admin/vendor/bshaffer/oauth2-server-php/src/OAuth2/Server.php",
    "line": 316,
    "stack-trace": [
        "#0 /Users/moment/work/code/work-jy/shop-admin/vendor/filsh/yii2-oauth2-server/Server.php(42): OAuth2\\Server->handleTokenRequest(Object(yii\\web\\Request), NULL)",
        "#1 /Users/moment/work/code/work-jy/shop-admin/vendor/filsh/yii2-oauth2-server/controllers/RestController.php(25): filsh\\yii2\\oauth2server\\Server->handleTokenRequest()",
        "#2 [internal function]: filsh\\yii2\\oauth2server\\controllers\\RestController->actionToken()",
        "#3 /Users/moment/work/code/work-jy/shop-admin/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)",
        "#4 /Users/moment/work/code/work-jy/shop-admin/vendor/yiisoft/yii2/base/Controller.php(157): yii\\base\\InlineAction->runWithParams(Array)",
        "#5 /Users/moment/work/code/work-jy/shop-admin/vendor/yiisoft/yii2/base/Module.php(528): yii\\base\\Controller->runAction('token', Array)",
        "#6 /Users/moment/work/code/work-jy/shop-admin/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module->runAction('oauth2/rest/tok...', Array)",
        "#7 /Users/moment/work/code/work-jy/shop-admin/vendor/yiisoft/yii2/base/Application.php(386): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))",
        "#8 /Users/moment/work/code/work-jy/shop-admin/api/web/index.php(17): yii\\base\\Application->run()",
        "#9 {main}"
    ]
}
```

```php
    public function handleTokenRequest(\OAuth2\RequestInterface $request = null, \OAuth2\ResponseInterface $response = null)
    {
        if($request === null) {
            $request = $this->module->getRequest();
        }
        return parent::handleTokenRequest($request, $response);
    }
```

**Comment by mtangoo** [comment] 2018-06-13 13:27
Hi,
I will check this later at home and fix it.
Thanks for reporting

**Comment by mtangoo** [comment] 2018-06-15 08:01
Please run `composer update` and test to see if the problem is fixed

**Comment by mtangoo** [comment] 2018-06-16 09:40
I will close this. feel free to re-open it in case your problem is not solved

**Closed as completed** 2018-06-16 09:39 UTC
Labels: bug
